AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless app template.

Parameters:

  # Code Pipeline passes this in via the "deploy" stage.
  ApplicationName:
    Type: String
    Description: Name of the serverless application.
    Default: WfuAitApp

  # Code Pipeline passes this in via the "deploy" stage.
  EnvironmentName:
    Type: String
    Description: Name of the application environment (dev, uat or prod).
    Default: dev
    AllowedValues:
      - dev
      - uat
      - prod

Conditions:

  # Environment Conditions
  IsDev: !Equals 
    - !Ref EnvironmentName
    - dev
  IsUat: !Equals 
    - !Ref EnvironmentName
    - uat
  IsProd: !Equals 
    - !Ref EnvironmentName
    - prod

Globals:

  # Defaults for all APIs.
  Api:
    OpenApiVersion: 3.0.1 # to avoid default stage creation
    
  # Defaults for all Lambda functions.
  Function:
    Handler: index.handler
    MemorySize: 1024
    Runtime: nodejs12.x
    Timeout: 180
    Environment:
      Variables:
        ENVIRONMENT_NAME: !Ref EnvironmentName
        ENDPOINT_TYPE: ''
        ENDPOINT_GUID: ''
        ENDPOINT_REQUEST_CONTENT: ''
    Layers:
      - !If [IsProd, 'arn:aws:lambda:us-east-1:841310976649:layer:WfuGlobalFunctionsProd:1', !If [IsUat, 'arn:aws:lambda:us-east-1:841310976649:layer:WfuGlobalFunctionsUat:1', 'arn:aws:lambda:us-east-1:841310976649:layer:WfuGlobalFunctionsDev:5']]
    Tags:
      Application: !Ref ApplicationName
      Environment: !Ref EnvironmentName
      Service: AIT Serverless
      Team: UA-AIT

Resources:

# Need to finish adding to this before you can do the app stack.

  ########
  # APIs #
  ########

  ###########
  # Lambdas #
  ###########
  

  ##############
  # SNS Topics #
  ##############
  
  DeploymentAlertTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      Tags:
        - Key: Name
          Value: !If [IsProd, 'DeploymentAlertTopicProd', !If [IsUat, 'DeploymentAlertTopicUat', 'DeploymentAlertTopicDev']]
        - Key: Application
          Value: !Ref ApplicationName
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Service
          Value: AIT Serverless
        - Key: Team
          Value: UA-AIT

  DeploymentAlertSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint: 'ait-developers@wfu.edu'
      Protocol: 'email'
      TopicArn: !Ref DeploymentAlertTopic
